import type { Metadata } from "next";
import { Geist, Geist_Mono, Figtree } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { Header } from "@/lib/components/header";
import "dotenv/config";
import { isAuthenticated } from "@/lib/services/auctionsAuth";

const figtree = Figtree({ subsets: ["latin"], variable: "--font-sans" });

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "DarkBay App",
	description: "Generated by create next app",
};

export default async function RootLayout({ children }: LayoutProps<"/">) {

	const isAuth = await isAuthenticated();

	return (
		<html
			lang="en"
			className={cn(
				"h-full",
				"antialiased",
				geistSans.variable,
				geistMono.variable,
				"font-sans",
				figtree.variable,
			)}
		>
			<body className="min-h-full flex flex-col">
				<Header isAuthenticated={isAuth} />
				{children}
			</body>
		</html>
	);
}
